http:
  commHeader: {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36"}
  clientConfig:
    httpClient:
      connectionRequestTimeout: 500
      connectTimeout: 50000
      socketTimeout: 30000
      staleConnectionCheckEnabled: true
      maxTotal: 200
      defaultMaxPerRoute: 100
      header: {etag: "16e36-540b1498e39c0"}
    httpClient2:
      connectionRequestTimeout: 500
      connectTimeout: 50000
      socketTimeout: 30000
      staleConnectionCheckEnabled: true
      maxTotal: 200
      defaultMaxPerRoute: 100
      header: {etag: "16e36-540b1498e39c0"}