httpClientService:
  connectionRequestTimeout: 500
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  automaticRetries: false
  header: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67" }
myHttp:
  connectionRequestTimeout: 1000
  connectTimeout: 1000
  socketTimeout: 4000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  header: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67" }
  automaticRetries: false
logging:
  level:
    root: error
    com.github.shy526.autoconfigure.CloseExpiredConnectionsTask: info
    com.github.shy526.service.HttpClientService: debug