httpClientService:
  connectionRequestTimeout: 500
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  primary: true
  requestSentRetryEnabled: false
  closeTask:
    name: httpClient2-close-task
    idleTime: 4000
    initialDelay: 4000
    delay: 4000

httpClientService4:
  connectionRequestTimeout: 1
  connectTimeout: 5000
  socketTimeout: 30000
  validateAfterInactivity: 2000
  maxTotal: 200
  defaultMaxPerRoute: 100
  requestSentRetryEnabled: false
  closeTask:
    name: httpClient2-close-task
    idleTime: 4000
    initialDelay: 4000
    delay: 4000

logging:
  level:
    top.ccxh.httpclient.autoconfigure.CloseExpiredConnectionsTask: debug